# Generated by Django 4.2.4 on 2023-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart_page', '0002_alter_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_number',
            field=models.IntegerField(blank=True, default=380000000000, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
