# Generated by Django 4.2.4 on 2023-11-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
