# Generated by Django 4.2.5 on 2023-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
