# Generated by Django 4.2.5 on 2023-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0002_alter_main_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.IntegerField(default='http://localhost:8000/product_page1/'),
        ),
    ]
