# Generated by Django 4.2.5 on 2023-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0003_alter_main_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='image_path',
            field=models.CharField(default='http://localhost:8000/product_page1/', max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.IntegerField(),
        ),
    ]
